name: Update NRL Data Daily

on:
  schedule:
    # Run at 6 AM AEST (8 PM UTC previous day) every day
    - cron: '0 20 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 pandas
      
      - name: Fetch latest NRL data
        run: python scripts/fetch_nrl_data.py
      
      - name: Generate dashboard
        run: python scripts/generate_dashboard.py
      
      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update NRL data $(date +'%Y-%m-%d')" && git push)
